export const COM_SAVE_SEARCH_HISTORY = 'COM_SAVE_SEARCH_HISTORY' // 保存搜索历史
export const COM_DELETE_SEARCH_HISTORY = 'COM_DELETE_SEARCH_HISTORY' //删除搜索历史
export const COM_CLEAR_SEARCH_HISTORY = 'COM_CLEAR_SEARCH_HISTORY' //清空所有搜索历史